/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/answers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          updated_at?: parameters["rowFilter.answers.updated_at"];
          user_id?: parameters["rowFilter.answers.user_id"];
          project_id?: parameters["rowFilter.answers.project_id"];
          task_id?: parameters["rowFilter.answers.task_id"];
          status?: parameters["rowFilter.answers.status"];
          attributes?: parameters["rowFilter.answers.attributes"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["answers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** answers */
          answers?: definitions["answers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          updated_at?: parameters["rowFilter.answers.updated_at"];
          user_id?: parameters["rowFilter.answers.user_id"];
          project_id?: parameters["rowFilter.answers.project_id"];
          task_id?: parameters["rowFilter.answers.task_id"];
          status?: parameters["rowFilter.answers.status"];
          attributes?: parameters["rowFilter.answers.attributes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.answers.id"];
          created_at?: parameters["rowFilter.answers.created_at"];
          updated_at?: parameters["rowFilter.answers.updated_at"];
          user_id?: parameters["rowFilter.answers.user_id"];
          project_id?: parameters["rowFilter.answers.project_id"];
          task_id?: parameters["rowFilter.answers.task_id"];
          status?: parameters["rowFilter.answers.status"];
          attributes?: parameters["rowFilter.answers.attributes"];
        };
        body: {
          /** answers */
          answers?: definitions["answers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/project_with_author_and_tasks": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.project_with_author_and_tasks.id"];
          created_at?: parameters["rowFilter.project_with_author_and_tasks.created_at"];
          updated_at?: parameters["rowFilter.project_with_author_and_tasks.updated_at"];
          status?: parameters["rowFilter.project_with_author_and_tasks.status"];
          attributes?: parameters["rowFilter.project_with_author_and_tasks.attributes"];
          author?: parameters["rowFilter.project_with_author_and_tasks.author"];
          tasks_count?: parameters["rowFilter.project_with_author_and_tasks.tasks_count"];
          tasks?: parameters["rowFilter.project_with_author_and_tasks.tasks"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["project_with_author_and_tasks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
  };
  "/projects": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          user_id?: parameters["rowFilter.projects.user_id"];
          status?: parameters["rowFilter.projects.status"];
          attributes?: parameters["rowFilter.projects.attributes"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["projects"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          user_id?: parameters["rowFilter.projects.user_id"];
          status?: parameters["rowFilter.projects.status"];
          attributes?: parameters["rowFilter.projects.attributes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          user_id?: parameters["rowFilter.projects.user_id"];
          status?: parameters["rowFilter.projects.status"];
          attributes?: parameters["rowFilter.projects.attributes"];
        };
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/projects_with_author_and_tasks_count": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects_with_author_and_tasks_count.id"];
          created_at?: parameters["rowFilter.projects_with_author_and_tasks_count.created_at"];
          attributes?: parameters["rowFilter.projects_with_author_and_tasks_count.attributes"];
          author?: parameters["rowFilter.projects_with_author_and_tasks_count.author"];
          tasks_count?: parameters["rowFilter.projects_with_author_and_tasks_count.tasks_count"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["projects_with_author_and_tasks_count"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
  };
  "/tasks": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          updated_at?: parameters["rowFilter.tasks.updated_at"];
          user_id?: parameters["rowFilter.tasks.user_id"];
          project_id?: parameters["rowFilter.tasks.project_id"];
          status?: parameters["rowFilter.tasks.status"];
          attributes?: parameters["rowFilter.tasks.attributes"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tasks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tasks */
          tasks?: definitions["tasks"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          updated_at?: parameters["rowFilter.tasks.updated_at"];
          user_id?: parameters["rowFilter.tasks.user_id"];
          project_id?: parameters["rowFilter.tasks.project_id"];
          status?: parameters["rowFilter.tasks.status"];
          attributes?: parameters["rowFilter.tasks.attributes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          updated_at?: parameters["rowFilter.tasks.updated_at"];
          user_id?: parameters["rowFilter.tasks.user_id"];
          project_id?: parameters["rowFilter.tasks.project_id"];
          status?: parameters["rowFilter.tasks.status"];
          attributes?: parameters["rowFilter.tasks.attributes"];
        };
        body: {
          /** tasks */
          tasks?: definitions["tasks"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** Answers for the project's tasks. */
  answers: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at?: string;
    user_id: string;
    /**
     * Note:
     * This is a Foreign Key to `projects.id`.<fk table='projects' column='id'/>
     */
    project_id: string;
    /**
     * Note:
     * This is a Foreign Key to `tasks.id`.<fk table='tasks' column='id'/>
     */
    task_id: string;
    status: number;
    attributes?: string;
  };
  project_with_author_and_tasks: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id?: string;
    created_at?: string;
    updated_at?: string;
    status?: number;
    attributes?: string;
    author?: string;
    tasks_count?: number;
    tasks?: string;
  };
  /** Projects created by users. */
  projects: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at?: string;
    updated_at?: string;
    user_id: string;
    status: number;
    attributes?: string;
  };
  projects_with_author_and_tasks_count: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id?: string;
    created_at?: string;
    attributes?: string;
    author?: string;
    tasks_count?: number;
  };
  /** Tasks for the project. */
  tasks: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at?: string;
    user_id: string;
    /**
     * Note:
     * This is a Foreign Key to `projects.id`.<fk table='projects' column='id'/>
     */
    project_id: string;
    status: number;
    attributes?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** answers */
  "body.answers": definitions["answers"];
  "rowFilter.answers.id": string;
  "rowFilter.answers.created_at": string;
  "rowFilter.answers.updated_at": string;
  "rowFilter.answers.user_id": string;
  "rowFilter.answers.project_id": string;
  "rowFilter.answers.task_id": string;
  "rowFilter.answers.status": string;
  "rowFilter.answers.attributes": string;
  /** project_with_author_and_tasks */
  "body.project_with_author_and_tasks": definitions["project_with_author_and_tasks"];
  "rowFilter.project_with_author_and_tasks.id": string;
  "rowFilter.project_with_author_and_tasks.created_at": string;
  "rowFilter.project_with_author_and_tasks.updated_at": string;
  "rowFilter.project_with_author_and_tasks.status": string;
  "rowFilter.project_with_author_and_tasks.attributes": string;
  "rowFilter.project_with_author_and_tasks.author": string;
  "rowFilter.project_with_author_and_tasks.tasks_count": string;
  "rowFilter.project_with_author_and_tasks.tasks": string;
  /** projects */
  "body.projects": definitions["projects"];
  "rowFilter.projects.id": string;
  "rowFilter.projects.created_at": string;
  "rowFilter.projects.updated_at": string;
  "rowFilter.projects.user_id": string;
  "rowFilter.projects.status": string;
  "rowFilter.projects.attributes": string;
  /** projects_with_author_and_tasks_count */
  "body.projects_with_author_and_tasks_count": definitions["projects_with_author_and_tasks_count"];
  "rowFilter.projects_with_author_and_tasks_count.id": string;
  "rowFilter.projects_with_author_and_tasks_count.created_at": string;
  "rowFilter.projects_with_author_and_tasks_count.attributes": string;
  "rowFilter.projects_with_author_and_tasks_count.author": string;
  "rowFilter.projects_with_author_and_tasks_count.tasks_count": string;
  /** tasks */
  "body.tasks": definitions["tasks"];
  "rowFilter.tasks.id": string;
  "rowFilter.tasks.created_at": string;
  "rowFilter.tasks.updated_at": string;
  "rowFilter.tasks.user_id": string;
  "rowFilter.tasks.project_id": string;
  "rowFilter.tasks.status": string;
  "rowFilter.tasks.attributes": string;
}

export interface operations {}

export interface external {}
